-- Synchronise le catalogue de code vers avatar_items (avec overlay_key renseigne).
-- Idempotent : ne reinsere pas un item deja present (meme overlay_key).
INSERT INTO public.avatar_items
  (name, name_fr, slot, rarity, pixel_art_data, unlock_method, is_premium, level_required)
SELECT v.name, v.name_fr, v.slot::item_slot, v.rarity::item_rarity, v.pixel_art_data::jsonb,
       v.unlock_method, v.is_premium, v.level_required
FROM (VALUES
('Scout Armor', 'Armure Éclaireur', 'body', 'common', '{"overlay_key":"skin_scout"}', 'level', false, 3),
('Martial Gi', 'Kimono de Combat', 'body', 'common', '{"overlay_key":"skin_martial"}', 'level', false, 6),
('Knight Plate', 'Armure de Chevalier', 'body', 'uncommon', '{"overlay_key":"skin_knight"}', 'level', false, 10),
('Monk Robe', 'Robe de Moine', 'body', 'uncommon', '{"overlay_key":"skin_monk"}', 'level', false, 15),
('Shadow Ninja', 'Ninja des Ombres', 'body', 'rare', '{"overlay_key":"skin_ninja"}', 'level', false, 25),
('Samurai Armor', 'Armure Samouraï', 'body', 'rare', '{"overlay_key":"skin_samurai"}', 'level', false, 30),
('Cyber Suit', 'Combinaison Cyber', 'body', 'rare', '{"overlay_key":"skin_cyber"}', 'level', false, 40),
('Shadow Form', 'Forme d''Ombre', 'body', 'epic', '{"overlay_key":"skin_shadow"}', 'level', false, 50),
('Royal Garments', 'Tenue Royale', 'body', 'epic', '{"overlay_key":"skin_royal"}', 'level', false, 60),
('Dragon Scale', 'Écailles de Dragon', 'body', 'epic', '{"overlay_key":"skin_dragon"}', 'level', false, 70),
('Phoenix Form', 'Forme Phénix', 'body', 'legendary', '{"overlay_key":"skin_phoenix"}', 'level', false, 85),
('Cosmic Form', 'Forme Cosmique', 'body', 'legendary', '{"overlay_key":"skin_cosmic"}', 'level', false, 95),
('Round Glasses', 'Lunettes Rondes', 'face', 'common', '{"overlay_key":"glasses_round"}', 'level', false, 5),
('Sunglasses', 'Lunettes de Soleil', 'face', 'common', '{"overlay_key":"sunglasses"}', 'level', false, 8),
('Battle Scar', 'Cicatrice', 'face', 'uncommon', '{"overlay_key":"scar"}', 'level', false, 20),
('Hero Mask', 'Masque de Héros', 'face', 'rare', '{"overlay_key":"mask_hero"}', 'level', false, 35),
('Monocle', 'Monocle', 'face', 'epic', '{"overlay_key":"monocle"}', 'level', false, 60),
('Traveler Cloak', 'Cape de Voyageur', 'cape', 'common', '{"overlay_key":"cape_traveler"}', 'level', false, 7),
('Red Cape', 'Cape Rouge', 'cape', 'uncommon', '{"overlay_key":"cape_red"}', 'level', false, 15),
('Royal Cape', 'Cape Royale', 'cape', 'epic', '{"overlay_key":"cape_royal"}', 'level', false, 50),
('Phoenix Wings', 'Ailes de Phénix', 'cape', 'legendary', '{"overlay_key":"cape_phoenix"}', 'level', false, 85),
('Wooden Stick', 'Bâton en Bois', 'weapon', 'common', '{"overlay_key":"stick_wood"}', 'level', false, 3),
('Iron Sword', 'Épée de Fer', 'weapon', 'uncommon', '{"overlay_key":"sword_iron"}', 'level', false, 10),
('Magic Staff', 'Bâton Magique', 'weapon', 'rare', '{"overlay_key":"staff_magic"}', 'level', false, 25),
('Flame Sword', 'Épée de Flamme', 'weapon', 'legendary', '{"overlay_key":"sword_flame"}', 'level', false, 75),
('Katana', 'Katana', 'weapon', 'epic', '{"overlay_key":"katana"}', 'level', false, 55),
('Calm Aura', 'Aura de Calme', 'aura', 'uncommon', '{"overlay_key":"aura_calm"}', 'level', false, 15),
('Fire Aura', 'Aura de Feu', 'aura', 'rare', '{"overlay_key":"aura_fire"}', 'level', false, 30),
('Ice Aura', 'Aura de Glace', 'aura', 'epic', '{"overlay_key":"aura_ice"}', 'level', false, 50),
('Cosmic Aura', 'Aura Cosmique', 'aura', 'legendary', '{"overlay_key":"aura_cosmic"}', 'level', false, 90),
('couronne fer', 'Couronne de Fer', 'head', 'common', '{"overlay_key":"couronne_fer"}', 'level', false, 8),
('couronne bronze', 'Couronne de Bronze', 'head', 'uncommon', '{"overlay_key":"couronne_bronze"}', 'level', false, 14),
('couronne argent', 'Couronne d''Argent', 'head', 'rare', '{"overlay_key":"couronne_argent"}', 'level', false, 22),
('couronne or', 'Couronne d''Or', 'head', 'epic', '{"overlay_key":"couronne_or"}', 'level', false, 34),
('couronne obsidienne', 'Couronne d''Obsidienne', 'head', 'legendary', '{"overlay_key":"couronne_obsidienne"}', 'level', false, 50),
('capuche fer', 'Capuche de Fer', 'head', 'common', '{"overlay_key":"capuche_fer"}', 'level', false, 4),
('capuche bronze', 'Capuche de Bronze', 'head', 'uncommon', '{"overlay_key":"capuche_bronze"}', 'level', false, 10),
('capuche argent', 'Capuche d''Argent', 'head', 'rare', '{"overlay_key":"capuche_argent"}', 'level', false, 18),
('capuche or', 'Capuche d''Or', 'head', 'epic', '{"overlay_key":"capuche_or"}', 'level', false, 30),
('capuche obsidienne', 'Capuche d''Obsidienne', 'head', 'legendary', '{"overlay_key":"capuche_obsidienne"}', 'level', false, 46),
('heaume fer', 'Heaume de Fer', 'head', 'common', '{"overlay_key":"heaume_fer"}', 'level', false, 12),
('heaume bronze', 'Heaume de Bronze', 'head', 'uncommon', '{"overlay_key":"heaume_bronze"}', 'level', false, 18),
('heaume argent', 'Heaume d''Argent', 'head', 'rare', '{"overlay_key":"heaume_argent"}', 'level', false, 26),
('heaume or', 'Heaume d''Or', 'head', 'epic', '{"overlay_key":"heaume_or"}', 'level', false, 38),
('heaume obsidienne', 'Heaume d''Obsidienne', 'head', 'legendary', '{"overlay_key":"heaume_obsidienne"}', 'level', false, 54),
('aureole fer', 'Auréole de Fer', 'head', 'common', '{"overlay_key":"aureole_fer"}', 'level', false, 20),
('aureole bronze', 'Auréole de Bronze', 'head', 'uncommon', '{"overlay_key":"aureole_bronze"}', 'level', false, 26),
('aureole argent', 'Auréole d''Argent', 'head', 'rare', '{"overlay_key":"aureole_argent"}', 'level', false, 34),
('aureole or', 'Auréole d''Or', 'head', 'epic', '{"overlay_key":"aureole_or"}', 'level', false, 46),
('aureole obsidienne', 'Auréole d''Obsidienne', 'head', 'legendary', '{"overlay_key":"aureole_obsidienne"}', 'level', false, 62),
('bandeau fer', 'Bandeau de Fer', 'head', 'common', '{"overlay_key":"bandeau_fer"}', 'level', false, 2),
('bandeau bronze', 'Bandeau de Bronze', 'head', 'uncommon', '{"overlay_key":"bandeau_bronze"}', 'level', false, 8),
('bandeau argent', 'Bandeau d''Argent', 'head', 'rare', '{"overlay_key":"bandeau_argent"}', 'level', false, 16),
('bandeau or', 'Bandeau d''Or', 'head', 'epic', '{"overlay_key":"bandeau_or"}', 'level', false, 28),
('bandeau obsidienne', 'Bandeau d''Obsidienne', 'head', 'legendary', '{"overlay_key":"bandeau_obsidienne"}', 'level', false, 44),
('chapeau_mage fer', 'Chapeau de Mage de Fer', 'head', 'common', '{"overlay_key":"chapeau_mage_fer"}', 'level', false, 16),
('chapeau_mage bronze', 'Chapeau de Mage de Bronze', 'head', 'uncommon', '{"overlay_key":"chapeau_mage_bronze"}', 'level', false, 22),
('chapeau_mage argent', 'Chapeau de Mage d''Argent', 'head', 'rare', '{"overlay_key":"chapeau_mage_argent"}', 'level', false, 30),
('chapeau_mage or', 'Chapeau de Mage d''Or', 'head', 'epic', '{"overlay_key":"chapeau_mage_or"}', 'level', false, 42),
('chapeau_mage obsidienne', 'Chapeau de Mage d''Obsidienne', 'head', 'legendary', '{"overlay_key":"chapeau_mage_obsidienne"}', 'level', false, 58),
('cornes fer', 'Cornes de Fer', 'head', 'common', '{"overlay_key":"cornes_fer"}', 'level', false, 18),
('cornes bronze', 'Cornes de Bronze', 'head', 'uncommon', '{"overlay_key":"cornes_bronze"}', 'level', false, 24),
('cornes argent', 'Cornes d''Argent', 'head', 'rare', '{"overlay_key":"cornes_argent"}', 'level', false, 32),
('cornes or', 'Cornes d''Or', 'head', 'epic', '{"overlay_key":"cornes_or"}', 'level', false, 44),
('cornes obsidienne', 'Cornes d''Obsidienne', 'head', 'legendary', '{"overlay_key":"cornes_obsidienne"}', 'level', false, 60),
('diademe fer', 'Diadème de Fer', 'head', 'common', '{"overlay_key":"diademe_fer"}', 'level', false, 10),
('diademe bronze', 'Diadème de Bronze', 'head', 'uncommon', '{"overlay_key":"diademe_bronze"}', 'level', false, 16),
('diademe argent', 'Diadème d''Argent', 'head', 'rare', '{"overlay_key":"diademe_argent"}', 'level', false, 24),
('diademe or', 'Diadème d''Or', 'head', 'epic', '{"overlay_key":"diademe_or"}', 'level', false, 36),
('diademe obsidienne', 'Diadème d''Obsidienne', 'head', 'legendary', '{"overlay_key":"diademe_obsidienne"}', 'level', false, 52),
('ailes_ange plume', 'Ailes de Plume', 'back', 'uncommon', '{"overlay_key":"ailes_ange_plume"}', 'level', false, 14),
('ailes_ange ombre', 'Ailes d''Ombre', 'back', 'rare', '{"overlay_key":"ailes_ange_ombre"}', 'level', false, 24),
('ailes_ange braise', 'Ailes de Braise', 'back', 'epic', '{"overlay_key":"ailes_ange_braise"}', 'level', false, 38),
('ailes_ange astre', 'Ailes d''Astre', 'back', 'legendary', '{"overlay_key":"ailes_ange_astre"}', 'level', false, 54),
('ailes_larges plume', 'Grandes Ailes de Plume', 'back', 'uncommon', '{"overlay_key":"ailes_larges_plume"}', 'level', false, 24),
('ailes_larges ombre', 'Grandes Ailes d''Ombre', 'back', 'rare', '{"overlay_key":"ailes_larges_ombre"}', 'level', false, 34),
('ailes_larges braise', 'Grandes Ailes de Braise', 'back', 'epic', '{"overlay_key":"ailes_larges_braise"}', 'level', false, 48),
('ailes_larges astre', 'Grandes Ailes d''Astre', 'back', 'legendary', '{"overlay_key":"ailes_larges_astre"}', 'level', false, 64),
('ailes_dechirees plume', 'Ailes Déchirées de Plume', 'back', 'uncommon', '{"overlay_key":"ailes_dechirees_plume"}', 'level', false, 20),
('ailes_dechirees ombre', 'Ailes Déchirées d''Ombre', 'back', 'rare', '{"overlay_key":"ailes_dechirees_ombre"}', 'level', false, 30),
('ailes_dechirees braise', 'Ailes Déchirées de Braise', 'back', 'epic', '{"overlay_key":"ailes_dechirees_braise"}', 'level', false, 44),
('ailes_dechirees astre', 'Ailes Déchirées d''Astre', 'back', 'legendary', '{"overlay_key":"ailes_dechirees_astre"}', 'level', false, 60),
('manteau_dos plume', 'Manteau de Plume', 'back', 'uncommon', '{"overlay_key":"manteau_dos_plume"}', 'level', false, 6),
('manteau_dos ombre', 'Manteau d''Ombre', 'back', 'rare', '{"overlay_key":"manteau_dos_ombre"}', 'level', false, 16),
('manteau_dos braise', 'Manteau de Braise', 'back', 'epic', '{"overlay_key":"manteau_dos_braise"}', 'level', false, 30),
('manteau_dos astre', 'Manteau d''Astre', 'back', 'legendary', '{"overlay_key":"manteau_dos_astre"}', 'level', false, 46),
('orbes plume', 'Orbes Gardiens de Plume', 'back', 'uncommon', '{"overlay_key":"orbes_plume"}', 'level', false, 30),
('orbes ombre', 'Orbes Gardiens d''Ombre', 'back', 'rare', '{"overlay_key":"orbes_ombre"}', 'level', false, 40),
('orbes braise', 'Orbes Gardiens de Braise', 'back', 'epic', '{"overlay_key":"orbes_braise"}', 'level', false, 54),
('orbes astre', 'Orbes Gardiens d''Astre', 'back', 'legendary', '{"overlay_key":"orbes_astre"}', 'level', false, 70),
('Moon', 'Lune Veilleuse', 'background', 'uncommon', '{"overlay_key":"background_lune"}', 'level', false, 9),
('Stars', 'Voûte Étoilée', 'background', 'common', '{"overlay_key":"background_etoiles"}', 'level', false, 5),
('Aurora', 'Aurore', 'background', 'rare', '{"overlay_key":"background_aurore"}', 'level', false, 28),
('Peaks', 'Cimes Lointaines', 'background', 'uncommon', '{"overlay_key":"background_montagne"}', 'level', false, 13),
('Portal', 'Portail d''Âme', 'background', 'epic', '{"overlay_key":"background_portail"}', 'level', false, 45),
('Starfall', 'Pluie d''Étoiles', 'background', 'legendary', '{"overlay_key":"background_pluie"}', 'level', false, 60),
('Cat', 'Chat de Nuit', 'pet', 'uncommon', '{"overlay_key":"pet_chat"}', 'level', false, 7),
('Fox', 'Renard Roux', 'pet', 'uncommon', '{"overlay_key":"pet_renard"}', 'level', false, 11),
('Raven', 'Corbeau Messager', 'pet', 'rare', '{"overlay_key":"pet_corbeau"}', 'level', false, 19),
('Wolf', 'Loup Gardien', 'pet', 'rare', '{"overlay_key":"pet_loup"}', 'level', false, 25),
('Wisp', 'Feu Follet', 'pet', 'epic', '{"overlay_key":"pet_wisp"}', 'level', false, 33),
('Drakeling', 'Dragonnet', 'pet', 'epic', '{"overlay_key":"pet_dragonnet"}', 'level', false, 40),
('Phoenix', 'Phénix Naissant', 'pet', 'legendary', '{"overlay_key":"pet_phenix"}', 'level', false, 52),
('Spirit', 'Esprit Ancestral', 'pet', 'mythic', '{"overlay_key":"pet_esprit"}', 'level', false, 75),
('Mythic Form', 'Forme Mythique', 'body', 'mythic', '{"overlay_key":"skin_mythic"}', 'level', true, 1),
('Mythic Aura', 'Aura Mythique', 'aura', 'mythic', '{"overlay_key":"aura_mythic"}', 'level', true, 1)
) AS v(name, name_fr, slot, rarity, pixel_art_data, unlock_method, is_premium, level_required)
WHERE NOT EXISTS (
  SELECT 1 FROM public.avatar_items a
  WHERE a.pixel_art_data->>'overlay_key' = v.pixel_art_data::jsonb->>'overlay_key'
);
